### ISSUE TITLE
Dotnet Tool

### ISSUE THREAD

**Issue by dersia** [hez2010/TypedocConverter#22]
First of all, thanks for this tool. I would like to use this in a ci scenario and for this it would be great to have this as a global dotnet tool (https://learn.microsoft.com/en-us/dotnet/core/tools/global-tools).

So I would like to request/suggest a deployment of this as a global dotnet tool next to the releases on github, so it can be installed during ci builds.

**Comment by hez2010** [comment]
Sounds great. Will set up some time to publish TypedocConverter as a dotnet tool.
Thanks for the idea.

**Comment by hez2010** [comment]
Hello,
It's now online on nuget.org: https://www.nuget.org/packages/TypedocConverter
