### ISSUE TITLE
Not all Types are Getting Generated

### ISSUE THREAD

**Issue by softworkz** [hez2010/TypedocConverter#3]
For example, look for dxDataGrid in the following json:

[dxall.zip](https://github.com/hez2010/TypedocConverter/files/4461005/dxall.zip)

Path: Globals.DevExpress.ui.dxDataGrid 

It is correctly shown in the docs generated from typedoc.

**Comment by hez2010** [comment]
Seems that TypedocConverter doesn't support nested classes for now. I'll add the support as soon as possible.

**Comment by hez2010** [comment]
Fixed via e5490e0

**Comment by softworkz** [comment]
I was about to write
~~Thanks for the quick response!~~

But wow - that was quick! :-)

**Comment by hez2010** [comment]
However, currently behavior of nested classes generation is generating classes under a namespace named same as its parent class'name.

**Comment by softworkz** [comment]
That doesn't matter at all - with R# I can move things easily :-)

**Comment by softworkz** [comment]
I can confirm that it's working now!

I've tried a dozen other ways to get proper C# classes from TS.
This is the first method that really works.

Great Job!

**Comment by hez2010** [comment]
Glad to see it's working for you. Enjoy :)

**Comment by softworkz** [comment]
Not that it's perfect - I had to fix hundreds of problems manually. The file I posted is an extreme example I guess. Probably good for testing.
But as I only needed a certain subset it was still fine for me.

**Comment by hez2010** [comment]
TypedocConverter only guarantees generated C# code is syntactically correct. It won't any type checking during code generation because not all TypeScript code can be written as C#, and .NET doesn't have types for DOM API either.

**Comment by hez2010** [comment]
I've added an issue to track changes of currently behavior, see #4.

**Comment by softworkz** [comment]
The most tedious work was to remove the nullable reference type annotations as I needed to create a netstandard2.0 class library.
It would be great when there would be an option for it.

**Comment by softworkz** [comment]
Similar goes for the NewtonSoft attributes, I had to replace/refactor all of them because we don't use NewtonSoft.

And another cool thing would be to output a list of unknown types. That would make it easier to create a number of empty classes for them or to look up which other definitions may need to be included.

**Comment by hez2010** [comment]
> It would be great when there would be an option for it.
>
> Similar goes for the NewtonSoft attributes, I had to replace/refactor all of them because we don't use NewtonSoft.
> 
> And another cool thing would be to output a list of unknown types. That would make it easier to create a number of empty classes for them or to look up which other definitions may need to be included.


Thanks. Related issues have been added for tracking.

**Comment by hez2010** [comment]
@softworkz I've added support for NRT and System.Text.Json, could you try again with those new options?

**Comment by softworkz** [comment]
Unfortunately I have already overused my time for this a bit and I have already invested too much time for manual editing.

My use case is a but special anyway, I guess. I'm not into some JS/C# convergence like Bridge.NET, I rather use the options models for those JS controls as C# models in order to configure them at the server side.

I still got some more feedback, though, matching the title of this issue:


1. For properties like the following, no types are created:

![image](https://user-images.githubusercontent.com/4985349/79049263-dc997c00-7c22-11ea-9738-5042f907a6ea.png)

The property is generated as 'object' only.


2. Constructors are not being generated:

![image](https://user-images.githubusercontent.com/4985349/79049281-03f04900-7c23-11ea-92eb-06f359e80b37.png)

**Comment by hez2010** [comment]
Really thanks for your feedback.

For issues you've mentioned:
1. Anonymous interfaces and union types are not supported for now, support for them will be shipped in future releases.
2. Constructors are being ignored because TypedocConverter is more like a tool to generate interfaces and be used to interop with JS, but I'll consider it in future releases.
