### ISSUE TITLE
Full support of union types

### ISSUE THREAD

**Issue by hez2010** [hez2010/TypedocConverter#5]
Currently we use a type selector (see https://github.com/hez2010/TypedocConverter/blob/e5490e05e92215c9856aedd09f806b4ee67af02c/TypedocConverter/Helpers.fs#L209 and https://github.com/hez2010/TypedocConverter/blob/e5490e05e92215c9856aedd09f806b4ee67af02c/TypedocConverter/Helpers.fs#L120) to generate a "representative" type of a union type.

Full support of union types should be added (using struct and implicit casting).

**Comment by fgoulet** [comment]
This is a feature that would be really useful when converting complex typescript file definition.

**Comment by hez2010** [comment]
I'm planning to implement this in near future (maybe the next release), if anyone has interest on it, feel free to share ideas in https://github.com/hez2010/TypedocConverter/discussions/14.

**Comment by hez2010** [comment]
Fixed via 57d17ba60a4caf0f85c8c6c0991641e80a6a5bcd
